AnimationPointers:
	table_width 2, AnimationPointers

	dw EkansAnimation
	dw ArbokAnimation
	dw HoundourAnimation
	dw HoundoomAnimation
	dw BaltoyAnimation
	dw ClaydolAnimation
	dw BidoofAnimation
	dw BibarelAnimation
	dw FletchlingAnimation
	dw FletchindrAnimation
	dw TalonflameAnimation
	dw PidgeyAnimation
	dw PidgeottoAnimation
	dw PidgeotAnimation
	dw PichuAnimation
	dw PikachuAnimation
	dw RaichuAnimation
	dw SentretAnimation
	dw FurretAnimation
	dw CaterpieAnimation
	dw MetapodAnimation
	dw ButterfreeAnimation
	dw SurskitAnimation
	dw MasquerainAnimation
	dw GeodudeAnimation
	dw GravelerAnimation
	dw GolemAnimation
	dw ShinxAnimation
	dw LuxioAnimation
	dw LuxrayAnimation
	dw ZubatAnimation
	dw GolbatAnimation
	dw CrobatAnimation
	dw DunsparceAnimation
	dw DudnsparceAnimation
	dw MareepAnimation
	dw FlaaffyAnimation
	dw AmpharosAnimation
	dw WooperAnimation
	dw ClodsireAnimation
	dw GastlyAnimation
	dw HaunterAnimation
	dw GengarAnimation
	dw OnixAnimation
	dw SteelixAnimation
	dw UnownAnimation
	dw HoppipAnimation
	dw SkiploomAnimation
	dw JumpluffAnimation
	dw ApplinAnimation
	dw FlappleAnimation
	dw AppletunAnimation
	dw MagikarpAnimation
	dw GyaradosAnimation
	dw CorphishAnimation
	dw CrawdauntAnimation
	dw BuizelAnimation
	dw FloatzelAnimation
	dw RockruffAnimation
	dw Lycanroc1Animation
	dw Lycanroc2Animation
	dw Lycanroc3Animation
	dw AbraAnimation
	dw KadabraAnimation
	dw AlakazamAnimation
	dw DittoAnimation
	dw Nidoran_mAnimation
	dw NidorinoAnimation
	dw NidokingAnimation
	dw Nidoran_fAnimation
	dw NidorinaAnimation
	dw NidoqueenAnimation
	dw YanmaAnimation
	dw YanmegaAnimation
	dw NumelAnimation
	dw CameruptAnimation
	dw DrifloonAnimation
	dw DrifblimAnimation
	dw WobbuffetAnimation
	dw AronAnimation
	dw LaironAnimation
	dw AggronAnimation
	dw ShroomishAnimation
	dw BreloomAnimation
	dw BunearyAnimation
	dw LopunnyAnimation
	dw VenonatAnimation
	dw VenomothAnimation
	dw ScytherAnimation
	dw ScizorAnimation
	dw KleavorAnimation
	dw HeracrossAnimation
	dw KoffingAnimation
	dw WeezingAnimation
	dw MagnemiteAnimation
	dw MagnetonAnimation
	dw MagnezoneAnimation
	dw VulpixAnimation
	dw NinetalesAnimation
	dw GrowlitheAnimation
	dw ArcanineAnimation
	dw StantlerAnimation
	dw WyrdeerAnimation
	dw MankeyAnimation
	dw PrimeapeAnimation
	dw MachopAnimation
	dw MachokeAnimation
	dw MachampAnimation
	dw TyrogueAnimation
	dw HitmonleeAnimation
	dw HitmonchanAnimation
	dw HitmontopAnimation
	dw ExeggcuteAnimation
	dw ExeggutorAnimation
	dw GirafarigAnimation
	dw FarigirafAnimation
	dw SmeargleAnimation
	dw SkrelpAnimation
	dw DragalgeAnimation
	dw KrabbyAnimation
	dw KinglerAnimation
	dw StaryuAnimation
	dw StarmieAnimation
	dw CorsolaAnimation
	dw FeebasAnimation
	dw MiloticAnimation
	dw ChinchouAnimation
	dw LanturnAnimation
	dw TurtonatorAnimation
	dw DuraludonAnimation
	dw ConttoneeAnimation
	dw WhimsicottAnimation
	dw EeveeAnimation
	dw VaporeonAnimation
	dw JolteonAnimation
	dw FlareonAnimation
	dw EspeonAnimation
	dw UmbreonAnimation
	dw GlaceonAnimation
	dw LeafeonAnimation
	dw HorseaAnimation
	dw SeadraAnimation
	dw KingdraAnimation
	dw GligarAnimation
	dw GliscorAnimation
	dw SwinubAnimation
	dw PiloswineAnimation
	dw MamoswineAnimation
	dw SnoruntAnimation
	dw GlalieAnimation
	dw FroslassAnimation
	dw SkarmoryAnimation
	dw StunkyAnimation
	dw SkuntankAnimation
	dw CubchooAnimation
	dw BearticAnimation
	dw LotadAnimation
	dw LombreAnimation
	dw LudicoloAnimation
	dw DuskullAnimation
	dw DusclopsAnimation
	dw DusknoirAnimation
	dw RhyhornAnimation
	dw RhydonAnimation
	dw RhyperiorAnimation
	dw MurkrowAnimation
	dw HonchkrowAnimation
	dw SneaselAnimation
	dw WeavileAnimation
	dw MisdreavusAnimation
	dw MismagiusAnimation
	dw PorygonAnimation
	dw Porygon2Animation
	dw PorygonzAnimation
	dw LaprasAnimation
	dw AnorithAnimation
	dw ArmaldoAnimation
	dw LileepAnimation
	dw CradillyAnimation
	dw YirtougaAnimation
	dw CaracostaAnimation
	dw RotomAnimation
	dw RioluAnimation
	dw LucarioAnimation
	dw CarvanhaAnimation
	dw SharpedoAnimation
	dw KecleonAnimation
	dw LunatoneAnimation
	dw SolrockAnimation
	dw CroagunkAnimation
	dw ToxicroakAnimation
	dw TrapinchAnimation
	dw VibravaAnimation
	dw FlygonAnimation
	dw ElecrikeAnimation
	dw ManectricAnimation
	dw MaractusAnimation
	dw AbsolAnimation
	dw LarvestaAnimation
	dw VolcoronaAnimation
	dw SnomAnimation
	dw FrosmothAnimation
	dw SpiritombAnimation
	dw BulbasaurAnimation
	dw IvysaurAnimation
	dw VenusaurAnimation
	dw CharmanderAnimation
	dw CharmeleonAnimation
	dw CharizardAnimation
	dw SquirtleAnimation
	dw WartortleAnimation
	dw BlastoiseAnimation
	dw ChikoritaAnimation
	dw BayleefAnimation
	dw MeganiumAnimation
	dw CyndaquilAnimation
	dw QuilavaAnimation
	dw TyphlosionAnimation
	dw TotodileAnimation
	dw CroconawAnimation
	dw FeraligatrAnimation
	dw TreekoAnimation
	dw GrovyleAnimation
	dw SceptileAnimation
	dw TorchicAnimation
	dw CombuskenAnimation
	dw BlazikenAnimation
	dw MudkipAnimation
	dw MarshtompAnimation
	dw SwampertAnimation
	dw MunchlaxAnimation
	dw SnorlaxAnimation
	dw BagonAnimation
	dw ShelgonAnimation
	dw SalamenceAnimation
	dw LarvitarAnimation
	dw PupitarAnimation
	dw TyranitarAnimation
	dw DratiniAnimation
	dw DragonairAnimation
	dw DragoniteAnimation
	dw DeoxysAnimation
	dw HeatranAnimation
	dw ShayminAnimation
	dw CresseliaAnimation
	dw DarkraiAnimation
	dw IronthornsAnimation
	dw RegidragoAnimation
	dw RegilekiAnimation
	dw JirachiAnimation
	dw ManaphyAnimation
	dw CelebiAnimation
	dw MewAnimation

	assert_table_length NUM_POKEMON
