BitmasksPointers:
	table_width 2, BitmasksPointers

	dw EkansBitmasks
	dw ArbokBitmasks
	dw HoundourBitmasks
	dw HoundoomBitmasks
	dw BaltoyBitmasks
	dw ClaydolBitmasks
	dw BidoofBitmasks
	dw BibarelBitmasks
	dw FletchlingBitmasks
	dw FletchindrBitmasks
	dw TalonflameBitmasks
	dw PidgeyBitmasks
	dw PidgeottoBitmasks
	dw PidgeotBitmasks
	dw PichuBitmasks
	dw PikachuBitmasks
	dw RaichuBitmasks
	dw SentretBitmasks
	dw FurretBitmasks
	dw CaterpieBitmasks
	dw MetapodBitmasks
	dw ButterfreeBitmasks
	dw SurskitBitmasks
	dw MasquerainBitmasks
	dw GeodudeBitmasks
	dw GravelerBitmasks
	dw GolemBitmasks
	dw ShinxBitmasks
	dw LuxioBitmasks
	dw LuxrayBitmasks
	dw ZubatBitmasks
	dw GolbatBitmasks
	dw CrobatBitmasks
	dw DunsparceBitmasks
	dw DudnsparceBitmasks
	dw MareepBitmasks
	dw FlaaffyBitmasks
	dw AmpharosBitmasks
	dw WooperBitmasks
	dw QuagsireBitmasks
	dw GastlyBitmasks
	dw HaunterBitmasks
	dw GengarBitmasks
	dw OnixBitmasks
	dw SteelixBitmasks
	dw UnownBitmasks
	dw HoppipBitmasks
	dw SkiploomBitmasks
	dw JumpluffBitmasks
	dw ApplinBitmasks
	dw FlappleBitmasks
	dw AppletunBitmasks
	dw MagikarpBitmasks
	dw GyaradosBitmasks
	dw CorphishBitmasks
	dw CrawdauntBitmasks
	dw BuizelBitmasks
	dw FloatzelBitmasks
	dw RockruffBitmasks
	dw Lycanroc1Bitmasks
	dw Lycanroc2Bitmasks
	dw Lycanroc3Bitmasks
	dw AbraBitmasks
	dw KadabraBitmasks
	dw AlakazamBitmasks
	dw DittoBitmasks
	dw Nidoran_mBitmasks
	dw NidorinoBitmasks
	dw NidokingBitmasks
	dw Nidoran_fBitmasks
	dw NidorinaBitmasks
	dw NidoqueenBitmasks
	dw YanmaBitmasks
	dw YanmegaBitmasks
	dw NumelBitmasks
	dw CameruptBitmasks
	dw DrifloonBitmasks
	dw DrifblimBitmasks
	dw WobbuffetBitmasks
	dw AronBitmasks
	dw LaironBitmasks
	dw AggronBitmasks
	dw ShroomishBitmasks
	dw BreloomBitmasks
	dw BunearyBitmasks
	dw LopunnyBitmasks
	dw VenonatBitmasks
	dw VenomothBitmasks
	dw ScytherBitmasks
	dw ScizorBitmasks
	dw KleavorBitmasks
	dw HeracrossBitmasks
	dw KoffingBitmasks
	dw WeezingBitmasks
	dw MagnemiteBitmasks
	dw MagnetonBitmasks
	dw MagnezoneBitmasks
	dw VulpixBitmasks
	dw NinetalesBitmasks
	dw GrowlitheBitmasks
	dw ArcanineBitmasks
	dw StantlerBitmasks
	dw WyrdeerBitmasks
	dw MankeyBitmasks
	dw PrimeapeBitmasks
	dw MachopBitmasks
	dw MachokeBitmasks
	dw MachampBitmasks
	dw TyrogueBitmasks
	dw HitmonleeBitmasks
	dw HitmonchanBitmasks
	dw HitmontopBitmasks
	dw ExeggcuteBitmasks
	dw ExeggutorBitmasks
	dw GirafarigBitmasks
	dw FarigirafBitmasks
	dw SmeargleBitmasks
	dw TentacoolBitmasks
	dw TentacruelBitmasks
	dw KrabbyBitmasks
	dw KinglerBitmasks
	dw StaryuBitmasks
	dw StarmieBitmasks
	dw CorsolaBitmasks
	dw FeebasBitmasks
	dw MiloticBitmasks
	dw ChinchouBitmasks
	dw LanturnBitmasks
	dw SeelBitmasks
	dw DewgongBitmasks
	dw ConttoneeBitmasks
	dw WhimsicottBitmasks
	dw EeveeBitmasks
	dw VaporeonBitmasks
	dw JolteonBitmasks
	dw FlareonBitmasks
	dw EspeonBitmasks
	dw UmbreonBitmasks
	dw GlaceonBitmasks
	dw LeafeonBitmasks
	dw HorseaBitmasks
	dw SeadraBitmasks
	dw KingdraBitmasks
	dw GligarBitmasks
	dw GliscorBitmasks
	dw SwinubBitmasks
	dw PiloswineBitmasks
	dw MamoswineBitmasks
	dw SnoruntBitmasks
	dw GlalieBitmasks
	dw FroslassBitmasks
	dw SkarmoryBitmasks
	dw StunkyBitmasks
	dw SkuntankBitmasks
	dw CubchooBitmasks
	dw BearticBitmasks
	dw PonytaBitmasks
	dw RapidashBitmasks
	dw DuskullBitmasks
	dw DusclopsBitmasks
	dw DusknoirBitmasks
	dw RhyhornBitmasks
	dw RhydonBitmasks
	dw RhyperiorBitmasks
	dw MurkrowBitmasks
	dw HonchkrowBitmasks
	dw SneaselBitmasks
	dw WeavileBitmasks
	dw MisdreavusBitmasks
	dw MismagiusBitmasks
	dw PorygonBitmasks
	dw Porygon2Bitmasks
	dw PorygonzBitmasks
	dw LaprasBitmasks
	dw AnorithBitmasks
	dw ArmaldoBitmasks
	dw LileepBitmasks
	dw CradillyBitmasks
	dw YirtougaBitmasks
	dw CaracostaBitmasks
	dw RotomBitmasks
	dw RioluBitmasks
	dw LucarioBitmasks
	dw CarvanhaBitmasks
	dw SharpedoBitmasks
	dw KecleonBitmasks
	dw LunatoneBitmasks
	dw SolrockBitmasks
	dw CroagunkBitmasks
	dw ToxicroakBitmasks
	dw TrapinchBitmasks
	dw VibravaBitmasks
	dw FlygonBitmasks
	dw ElecrikeBitmasks
	dw ManectricBitmasks
	dw MaractusBitmasks
	dw AbsolBitmasks
	dw LarvestaBitmasks
	dw VolcoronaBitmasks
	dw SnomBitmasks
	dw FrosmothBitmasks
	dw SpiritombBitmasks
	dw BulbasaurBitmasks
	dw IvysaurBitmasks
	dw VenusaurBitmasks
	dw CharmanderBitmasks
	dw CharmeleonBitmasks
	dw CharizardBitmasks
	dw SquirtleBitmasks
	dw WartortleBitmasks
	dw BlastoiseBitmasks
	dw ChikoritaBitmasks
	dw BayleefBitmasks
	dw MeganiumBitmasks
	dw CyndaquilBitmasks
	dw QuilavaBitmasks
	dw TyphlosionBitmasks
	dw TotodileBitmasks
	dw CroconawBitmasks
	dw FeraligatrBitmasks
	dw TreekoBitmasks
	dw GrovyleBitmasks
	dw SceptileBitmasks
	dw TorchicBitmasks
	dw CombuskenBitmasks
	dw BlazikenBitmasks
	dw MudkipBitmasks
	dw MarshtompBitmasks
	dw SwampertBitmasks
	dw MunchlaxBitmasks
	dw SnorlaxBitmasks
	dw BagonBitmasks
	dw ShelgonBitmasks
	dw SalamenceBitmasks
	dw LarvitarBitmasks
	dw PupitarBitmasks
	dw TyranitarBitmasks
	dw DratiniBitmasks
	dw DragonairBitmasks
	dw DragoniteBitmasks
	dw DeoxysBitmasks
	dw HeatranBitmasks
	dw ShayminBitmasks
	dw CresseliaBitmasks
	dw DarkraiBitmasks
	dw IronthornsBitmasks
	dw RegidragoBitmasks
	dw RegilekiBitmasks
	dw JirachiBitmasks
	dw ManaphyBitmasks
	dw CelebiBitmasks
	dw MewBitmasks
	assert_table_length NUM_POKEMON
