FramesPointers:
	table_width 2, FramesPointers

	dw EkansFrames
	dw ArbokFrames
	dw HoundourFrames
	dw HoundoomFrames
	dw BaltoyFrames
	dw ClaydolFrames
	dw BidoofFrames
	dw BibarelFrames
	dw FletchlingFrames
	dw FletchindrFrames
	dw TalonflameFrames
	dw PidgeyFrames
	dw PidgeottoFrames
	dw PidgeotFrames
	dw PichuFrames
	dw PikachuFrames
	dw RaichuFrames
	dw SentretFrames
	dw FurretFrames
	dw CaterpieFrames
	dw MetapodFrames
	dw ButterfreeFrames
	dw SurskitFrames
	dw MasquerainFrames
	dw GeodudeFrames
	dw GravelerFrames
	dw GolemFrames
	dw ShinxFrames
	dw LuxioFrames
	dw LuxrayFrames
	dw ZubatFrames
	dw GolbatFrames
	dw CrobatFrames
	dw DunsparceFrames
	dw DudnsparceFrames
	dw MareepFrames
	dw FlaaffyFrames
	dw AmpharosFrames
	dw WooperFrames
	dw ClodsireFrames
	dw GastlyFrames
	dw HaunterFrames
	dw GengarFrames
	dw OnixFrames
	dw SteelixFrames
	dw UnownFrames
	dw HoppipFrames
	dw SkiploomFrames
	dw JumpluffFrames
	dw ApplinFrames
	dw FlappleFrames
	dw AppletunFrames
	dw MagikarpFrames
	dw GyaradosFrames
	dw CorphishFrames
	dw CrawdauntFrames
	dw BuizelFrames
	dw FloatzelFrames
	dw RockruffFrames
	dw Lycanroc1Frames
	dw Lycanroc2Frames
	dw Lycanroc3Frames
	dw AbraFrames
	dw KadabraFrames
	dw AlakazamFrames
	dw DittoFrames
	dw Nidoran_mFrames
	dw NidorinoFrames
	dw NidokingFrames
	dw Nidoran_fFrames
	dw NidorinaFrames
	dw NidoqueenFrames
	dw YanmaFrames
	dw YanmegaFrames
	dw NumelFrames
	dw CameruptFrames
	dw DrifloonFrames
	dw DrifblimFrames
	dw WobbuffetFrames
	dw AronFrames
	dw LaironFrames
	dw AggronFrames
	dw ShroomishFrames
	dw BreloomFrames
	dw BunearyFrames
	dw LopunnyFrames
	dw VenonatFrames
	dw VenomothFrames
	dw ScytherFrames
	dw ScizorFrames
	dw KleavorFrames
	dw HeracrossFrames
	dw KoffingFrames
	dw WeezingFrames
	dw MagnemiteFrames
	dw MagnetonFrames
	dw MagnezoneFrames
	dw VulpixFrames
	dw NinetalesFrames
	dw GrowlitheFrames
	dw ArcanineFrames
	dw StantlerFrames
	dw WyrdeerFrames
	dw MankeyFrames
	dw PrimeapeFrames
	dw MachopFrames
	dw MachokeFrames
	dw MachampFrames
	dw TyrogueFrames
	dw HitmonleeFrames
	dw HitmonchanFrames
	dw HitmontopFrames
	dw ExeggcuteFrames
	dw ExeggutorFrames
	dw GirafarigFrames
	dw FarigirafFrames
	dw SmeargleFrames
	dw SkrelpFrames
	dw DragalgeFrames
	dw KrabbyFrames
	dw KinglerFrames
	dw StaryuFrames
	dw StarmieFrames
	dw CorsolaFrames
	dw FeebasFrames
	dw MiloticFrames
	dw ChinchouFrames
	dw LanturnFrames
	dw TurtonatorFrames
	dw DuraludonFrames
	dw ConttoneeFrames
	dw WhimsicottFrames
	dw EeveeFrames
	dw VaporeonFrames
	dw JolteonFrames
	dw FlareonFrames
	dw EspeonFrames
	dw UmbreonFrames
	dw GlaceonFrames
	dw LeafeonFrames
	dw HorseaFrames
	dw SeadraFrames
	dw KingdraFrames
	dw GligarFrames
	dw GliscorFrames
	dw SwinubFrames
	dw PiloswineFrames
	dw MamoswineFrames
	dw SnoruntFrames
	dw GlalieFrames
	dw FroslassFrames
	dw SkarmoryFrames
	dw StunkyFrames
	dw SkuntankFrames
	dw CubchooFrames
	dw BearticFrames
	dw LotadFrames
	dw LombreFrames
	dw LudicoloFrames
	dw DuskullFrames
	dw DusclopsFrames
	dw DusknoirFrames
	dw RhyhornFrames
	dw RhydonFrames
	dw RhyperiorFrames
	dw MurkrowFrames
	dw HonchkrowFrames
	dw SneaselFrames
	dw WeavileFrames
	dw MisdreavusFrames
	dw MismagiusFrames
	dw PorygonFrames
	dw Porygon2Frames
	dw PorygonzFrames
	dw LaprasFrames
	dw AnorithFrames
	dw ArmaldoFrames
	dw LileepFrames
	dw CradillyFrames
	dw YirtougaFrames
	dw CaracostaFrames
	dw RotomFrames
	dw RioluFrames
	dw LucarioFrames
	dw CarvanhaFrames
	dw SharpedoFrames
	dw KecleonFrames
	dw LunatoneFrames
	dw SolrockFrames
	dw CroagunkFrames
	dw ToxicroakFrames
	dw TrapinchFrames
	dw VibravaFrames
	dw FlygonFrames
	dw ElecrikeFrames
	dw ManectricFrames
	dw MaractusFrames
	dw AbsolFrames
	dw LarvestaFrames
	dw VolcoronaFrames
	dw SnomFrames
	dw FrosmothFrames
	dw SpiritombFrames
	dw BulbasaurFrames
	dw IvysaurFrames
	dw VenusaurFrames
	dw CharmanderFrames
	dw CharmeleonFrames
	dw CharizardFrames
	dw SquirtleFrames
	dw WartortleFrames
	dw BlastoiseFrames
	dw ChikoritaFrames
	dw BayleefFrames
	dw MeganiumFrames
	dw CyndaquilFrames
	dw QuilavaFrames
	dw TyphlosionFrames
	dw TotodileFrames
	dw CroconawFrames
	dw FeraligatrFrames
	dw TreekoFrames
	dw GrovyleFrames
	dw SceptileFrames
	dw TorchicFrames
	dw CombuskenFrames
	dw BlazikenFrames
	dw MudkipFrames
	dw MarshtompFrames
	dw SwampertFrames
	dw MunchlaxFrames
	dw SnorlaxFrames
	dw BagonFrames
	dw ShelgonFrames
	dw SalamenceFrames
	dw LarvitarFrames
	dw PupitarFrames
	dw TyranitarFrames
	dw DratiniFrames
	dw DragonairFrames
	dw DragoniteFrames
	dw DeoxysFrames
	dw HeatranFrames
	dw ShayminFrames
	dw CresseliaFrames
	dw DarkraiFrames
	dw IronthornsFrames
	dw RegidragoFrames
	dw RegilekiFrames
	dw JirachiFrames
	dw ManaphyFrames
	dw CelebiFrames
	dw MewFrames
	assert_table_length NUM_POKEMON
