AnimationIdlePointers:
	table_width 2, AnimationIdlePointers
	dw EkansAnimationIdle
	dw ArbokAnimationIdle
	dw HoundourAnimationIdle
	dw HoundoomAnimationIdle
	dw BaltoyAnimationIdle
	dw ClaydolAnimationIdle
	dw BidoofAnimationIdle
	dw BibarelAnimationIdle
	dw FletchlingAnimationIdle
	dw FletchindrAnimationIdle
	dw TalonflameAnimationIdle
	dw PidgeyAnimationIdle
	dw PidgeottoAnimationIdle
	dw PidgeotAnimationIdle
	dw PichuAnimationIdle
	dw PikachuAnimationIdle
	dw RaichuAnimationIdle
	dw SentretAnimationIdle
	dw FurretAnimationIdle
	dw CaterpieAnimationIdle
	dw MetapodAnimationIdle
	dw ButterfreeAnimationIdle
	dw SurskitAnimationIdle
	dw MasquerainAnimationIdle
	dw GeodudeAnimationIdle
	dw GravelerAnimationIdle
	dw GolemAnimationIdle
	dw ShinxAnimationIdle
	dw LuxioAnimationIdle
	dw LuxrayAnimationIdle
	dw ZubatAnimationIdle
	dw GolbatAnimationIdle
	dw CrobatAnimationIdle
	dw DunsparceAnimationIdle
	dw DudnsparceAnimationIdle
	dw MareepAnimationIdle
	dw FlaaffyAnimationIdle
	dw AmpharosAnimationIdle
	dw WooperAnimationIdle
	dw ClodsireAnimationIdle
	dw GastlyAnimationIdle
	dw HaunterAnimationIdle
	dw GengarAnimationIdle
	dw OnixAnimationIdle
	dw SteelixAnimationIdle
	dw UnownAnimationIdle
	dw HoppipAnimationIdle
	dw SkiploomAnimationIdle
	dw JumpluffAnimationIdle
	dw ApplinAnimationIdle
	dw FlappleAnimationIdle
	dw AppletunAnimationIdle
	dw MagikarpAnimationIdle
	dw GyaradosAnimationIdle
	dw CorphishAnimationIdle
	dw CrawdauntAnimationIdle
	dw BuizelAnimationIdle
	dw FloatzelAnimationIdle
	dw RockruffAnimationIdle
	dw Lycanroc1AnimationIdle
	dw Lycanroc2AnimationIdle
	dw Lycanroc3AnimationIdle
	dw AbraAnimationIdle
	dw KadabraAnimationIdle
	dw AlakazamAnimationIdle
	dw DittoAnimationIdle
	dw Nidoran_mAnimationIdle
	dw NidorinoAnimationIdle
	dw NidokingAnimationIdle
	dw Nidoran_fAnimationIdle
	dw NidorinaAnimationIdle
	dw NidoqueenAnimationIdle
	dw YanmaAnimationIdle
	dw YanmegaAnimationIdle
	dw NumelAnimationIdle
	dw CameruptAnimationIdle
	dw DrifloonAnimationIdle
	dw DrifblimAnimationIdle
	dw WobbuffetAnimationIdle
	dw AronAnimationIdle
	dw LaironAnimationIdle
	dw AggronAnimationIdle
	dw ShroomishAnimationIdle
	dw BreloomAnimationIdle
	dw BunearyAnimationIdle
	dw LopunnyAnimationIdle
	dw VenonatAnimationIdle
	dw VenomothAnimationIdle
	dw ScytherAnimationIdle
	dw ScizorAnimationIdle
	dw KleavorAnimationIdle
	dw HeracrossAnimationIdle
	dw KoffingAnimationIdle
	dw WeezingAnimationIdle
	dw MagnemiteAnimationIdle
	dw MagnetonAnimationIdle
	dw MagnezoneAnimationIdle
	dw VulpixAnimationIdle
	dw NinetalesAnimationIdle
	dw GrowlitheAnimationIdle
	dw ArcanineAnimationIdle
	dw StantlerAnimationIdle
	dw WyrdeerAnimationIdle
	dw MankeyAnimationIdle
	dw PrimeapeAnimationIdle
	dw MachopAnimationIdle
	dw MachokeAnimationIdle
	dw MachampAnimationIdle
	dw TyrogueAnimationIdle
	dw HitmonleeAnimationIdle
	dw HitmonchanAnimationIdle
	dw HitmontopAnimationIdle
	dw ExeggcuteAnimationIdle
	dw ExeggutorAnimationIdle
	dw GirafarigAnimationIdle
	dw FarigirafAnimationIdle
	dw SmeargleAnimationIdle
	dw SkrelpAnimationIdle
	dw DragalgeAnimationIdle
	dw KrabbyAnimationIdle
	dw KinglerAnimationIdle
	dw StaryuAnimationIdle
	dw StarmieAnimationIdle
	dw CorsolaAnimationIdle
	dw FeebasAnimationIdle
	dw MiloticAnimationIdle
	dw ChinchouAnimationIdle
	dw LanturnAnimationIdle
	dw TurtonatorAnimationIdle
	dw DuraludonAnimationIdle
	dw ConttoneeAnimationIdle
	dw WhimsicottAnimationIdle
	dw EeveeAnimationIdle
	dw VaporeonAnimationIdle
	dw JolteonAnimationIdle
	dw FlareonAnimationIdle
	dw EspeonAnimationIdle
	dw UmbreonAnimationIdle
	dw GlaceonAnimationIdle
	dw LeafeonAnimationIdle
	dw HorseaAnimationIdle
	dw SeadraAnimationIdle
	dw KingdraAnimationIdle
	dw GligarAnimationIdle
	dw GliscorAnimationIdle
	dw SwinubAnimationIdle
	dw PiloswineAnimationIdle
	dw MamoswineAnimationIdle
	dw SnoruntAnimationIdle
	dw GlalieAnimationIdle
	dw FroslassAnimationIdle
	dw SkarmoryAnimationIdle
	dw StunkyAnimationIdle
	dw SkuntankAnimationIdle
	dw CubchooAnimationIdle
	dw BearticAnimationIdle
	dw LotadAnimationIdle
	dw LombreAnimationIdle
	dw LudicoloAnimationIdle
	dw DuskullAnimationIdle
	dw DusclopsAnimationIdle
	dw DusknoirAnimationIdle
	dw RhyhornAnimationIdle
	dw RhydonAnimationIdle
	dw RhyperiorAnimationIdle
	dw MurkrowAnimationIdle
	dw HonchkrowAnimationIdle
	dw SneaselAnimationIdle
	dw WeavileAnimationIdle
	dw MisdreavusAnimationIdle
	dw MismagiusAnimationIdle
	dw PorygonAnimationIdle
	dw Porygon2AnimationIdle
	dw PorygonzAnimationIdle
	dw LaprasAnimationIdle
	dw AnorithAnimationIdle
	dw ArmaldoAnimationIdle
	dw LileepAnimationIdle
	dw CradillyAnimationIdle
	dw YirtougaAnimationIdle
	dw CaracostaAnimationIdle
	dw RotomAnimationIdle
	dw RioluAnimationIdle
	dw LucarioAnimationIdle
	dw CarvanhaAnimationIdle
	dw SharpedoAnimationIdle
	dw KecleonAnimationIdle
	dw LunatoneAnimationIdle
	dw SolrockAnimationIdle
	dw CroagunkAnimationIdle
	dw ToxicroakAnimationIdle
	dw TrapinchAnimationIdle
	dw VibravaAnimationIdle
	dw FlygonAnimationIdle
	dw ElecrikeAnimationIdle
	dw ManectricAnimationIdle
	dw MaractusAnimationIdle
	dw AbsolAnimationIdle
	dw LarvestaAnimationIdle
	dw VolcoronaAnimationIdle
	dw SnomAnimationIdle
	dw FrosmothAnimationIdle
	dw SpiritombAnimationIdle
	dw BulbasaurAnimationIdle
	dw IvysaurAnimationIdle
	dw VenusaurAnimationIdle
	dw CharmanderAnimationIdle
	dw CharmeleonAnimationIdle
	dw CharizardAnimationIdle
	dw SquirtleAnimationIdle
	dw WartortleAnimationIdle
	dw BlastoiseAnimationIdle
	dw ChikoritaAnimationIdle
	dw BayleefAnimationIdle
	dw MeganiumAnimationIdle
	dw CyndaquilAnimationIdle
	dw QuilavaAnimationIdle
	dw TyphlosionAnimationIdle
	dw TotodileAnimationIdle
	dw CroconawAnimationIdle
	dw FeraligatrAnimationIdle
	dw TreekoAnimationIdle
	dw GrovyleAnimationIdle
	dw SceptileAnimationIdle
	dw TorchicAnimationIdle
	dw CombuskenAnimationIdle
	dw BlazikenAnimationIdle
	dw MudkipAnimationIdle
	dw MarshtompAnimationIdle
	dw SwampertAnimationIdle
	dw MunchlaxAnimationIdle
	dw SnorlaxAnimationIdle
	dw BagonAnimationIdle
	dw ShelgonAnimationIdle
	dw SalamenceAnimationIdle
	dw LarvitarAnimationIdle
	dw PupitarAnimationIdle
	dw TyranitarAnimationIdle
	dw DratiniAnimationIdle
	dw DragonairAnimationIdle
	dw DragoniteAnimationIdle
	dw DeoxysAnimationIdle
	dw HeatranAnimationIdle
	dw ShayminAnimationIdle
	dw CresseliaAnimationIdle
	dw DarkraiAnimationIdle
	dw IronthornsAnimationIdle
	dw RegidragoAnimationIdle
	dw RegilekiAnimationIdle
	dw JirachiAnimationIdle
	dw ManaphyAnimationIdle
	dw CelebiAnimationIdle
	dw MewAnimationIdle
	assert_table_length NUM_POKEMON
